version:  "3.9"

services:
  discovery-service:
    image: "discovery-service:latest"
    build:
      context: .
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - mired
networks:
  mired:
    external: true